name: Build tree-sitter

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 2.2.0

      - name: Build
        run: |
          ./build.main.kts

      - name: Upload tree-sitters artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitters
          path: |
            build/**/*.dll
            build/**/*.dylib
            build/**/*.so
